export const PENDING = 'PENDING';
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const GET_PERSON_FAILED = 'GET_PERSON_FAILED';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILED = 'GET_PEOPLE_FAILED';
export const GET_STARSHIPS_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_STARSHIPS_FAILED = 'GET_PEOPLE_FAILED';